## KNN ALGORITHM


In [4]:
import numpy
import pandas as pd


from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import classification_report,confusion_matrix

iris = datasets.load_iris()
x    = iris.data
y    = iris.target

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.4)
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(x_train,y_train)
y_predict = classifier.predict(x_test)

print("Confusion Matrix")
print(confusion_matrix(y_test,y_predict))

Confusion Matrix
[[17  0  0]
 [ 0 20  2]
 [ 0  1 20]]


In [6]:
print("Accuracy Matrix")
print(classification_report(y_test,y_predict))

Accuracy Matrix
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.95      0.91      0.93        22
           2       0.91      0.95      0.93        21

    accuracy                           0.95        60
   macro avg       0.95      0.95      0.95        60
weighted avg       0.95      0.95      0.95        60

